import { jsPDF } from 'jspdf'

const MARGIN = 40
const PAGE_HEIGHT = 842
const PAGE_WIDTH = 595
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2
const BOTTOM_LIMIT = 800

const STATUS_LABELS = {
  todo:    'To do',
  doing:   'In progress',
  done:    'Done',
  skipped: 'Skipped',
}

function imageFormat(mimeType) {
  if (mimeType === 'image/jpeg' || mimeType === 'image/jpg') return 'JPEG'
  if (mimeType === 'image/png') return 'PNG'
  return null
}

/**
 * Pure builder — assembles and returns the jsPDF document. No side effects.
 */
export function buildChecklistPdf({ country, countryMeta, profile, docs, statuses, files }) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  let y = MARGIN

  // ── helpers ──────────────────────────────────────────────────────────────
  function ink()  { doc.setTextColor(30, 30, 30) }
  function muted(){ doc.setTextColor(136, 136, 136) }
  function checkPage(needed = 20) {
    if (y + needed > BOTTOM_LIMIT) {
      doc.addPage()
      y = MARGIN
    }
  }

  // ── 1. Header ─────────────────────────────────────────────────────────────
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(18)
  ink()
  doc.text(`VisaPrep — ${countryMeta.name} Tourist Visa Checklist`, MARGIN, y)
  y += 22

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  muted()
  const visaLine = `${countryMeta.visa} · Fee ${countryMeta.fee} · Processing ${countryMeta.proc}`
  doc.text(visaLine, MARGIN, y)
  y += 16

  // ── 2. Generated line ─────────────────────────────────────────────────────
  const dateStr = new Date().toLocaleDateString()
  doc.text(`Generated by VisaPrep · ${dateStr}`, MARGIN, y)
  y += 24

  // ── 3. Applicant section ──────────────────────────────────────────────────
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  ink()
  doc.text('Applicant', MARGIN, y)
  y += 16

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  const p = profile ?? {}
  const applicantLines = [
    `Passport: ${p.passport ?? '—'}`,
    `Purpose: ${p.purpose ?? '—'}`,
    `Length of stay: ${p.stay ?? '—'}`,
    `Travelling as: ${p.party ?? '—'}`,
    `Prior visa history: ${p.history ?? '—'}`,
  ]
  for (const line of applicantLines) {
    ink()
    doc.text(line, MARGIN, y)
    y += 14
  }
  y += 8

  // ── 4. Progress line ──────────────────────────────────────────────────────
  const doneCount = docs.filter((d) => statuses[d.id] === 'done').length
  muted()
  doc.setFontSize(10)
  doc.text(`${doneCount} of ${docs.length} documents ready`, MARGIN, y)
  y += 20

  // ── 5. Documents section ──────────────────────────────────────────────────
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  ink()
  doc.text('Documents', MARGIN, y)
  y += 18

  for (const d of docs) {
    checkPage(80)

    const tag      = d.required ? '[Required]' : '[Optional]'
    const statusKey = statuses[d.id] ?? 'todo'
    const label    = STATUS_LABELS[statusKey] ?? 'To do'
    const file     = files[d.id]
    const imgFmt   = file ? imageFormat(file.type) : null
    const thumbW   = 60
    const thumbH   = 60

    // Row: title
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(10)
    ink()
    doc.text(d.title, MARGIN, y)

    // Tag & status to the right
    doc.setFont('helvetica', 'normal')
    muted()
    const tagStatusStr = `${tag}  ${label}`
    const strWidth = doc.getTextWidth(tagStatusStr)
    doc.text(tagStatusStr, PAGE_WIDTH - MARGIN - strWidth, y)
    y += 14

    // File info line
    if (file) {
      doc.setFontSize(9)
      muted()
      if (file.type === 'application/pdf') {
        doc.text(`Uploaded: ${file.name}   (PDF attached separately)`, MARGIN, y)
        y += 13
      } else {
        doc.text(`Uploaded: ${file.name}`, MARGIN, y)
        y += 13

        // Thumbnail for images
        if (imgFmt && file.dataURL) {
          checkPage(thumbH + 8)
          try {
            doc.addImage(file.dataURL, imgFmt, MARGIN, y, thumbW, thumbH)
            y += thumbH + 6
          } catch {
            // malformed image — skip thumbnail silently
          }
        }
      }
    }

    y += 8
  }

  // ── 6. Footer disclaimer ──────────────────────────────────────────────────
  checkPage(20)
  doc.setFontSize(8)
  muted()
  doc.text(
    'Visa requirements change — always confirm on the official government website before applying.',
    MARGIN,
    y,
  )

  return doc
}

/**
 * Convenience wrapper — builds then triggers the browser download.
 */
export function downloadChecklistPdf(data) {
  const doc  = buildChecklistPdf(data)
  const name = `visaprep-${data.country}-checklist.pdf`
  doc.save(name)
}
